apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
name: argo-cd
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 2.11.0
    repository: https://argoproj.github.io/argo-helm